import { idScroll } from "@/utils/contants";

export const PRODUCTS = [
  {
    id: idScroll.ADMIN_EMPLOYEES,
    title: "admin employees",
    description:
      "This website is a user management system I developed, featuring login and content management functionalities. It offers an intuitive interface for administrators to monitor user activities and manage accounts efficiently.",
    tech_stack: ["NextJS", "TailwindCSS", "Shadcn/ui"],
    video_url: "/videos/admin-employees.mp4",
    time_line: "August 28th, 2024 - September 4th, 2024 (waiting for Backend)",
    deploy_url: "https://dao-duy-dien-frontend-web-app.vercel.app",
    source_url: "https://github.com/duydien0902/DaoDuyDien-FrontendWebApp",
    thumbnail: "/images/admin_employees.png",
    isDone: false,
  },
  {
    id: idScroll.TRELLO,
    title: "trello",
    description:
      "Trello is a flexible and powerful tool for project management, team collaboration, and effective task organization for both personal and team use.",
    tech_stack: [
      "Reactjs",
      "SCSS",
      "Bootstrap",
      "NodeJS",
      "ExpressJS",
      "Mongodb",
    ],
    video_url: "/videos/trello.mp4",
    time_line: "March 2023 - July 2023",
    deploy_url: "https://deploy-netlify--duydien0902-clonetrello.netlify.app",
    source_url: "https://github.com/duydien0902/Trello-clone",
    thumbnail: "/images/trello.png",
    isDone: true,
  },
  {
    id: idScroll.PHARMACITY,
    title: "pharmacity",
    description: "Replicate the Pharmacity e-commerce website.",
    tech_stack: ["NextJS", "TailwindCSS", "Shadcn/ui"],
    video_url: "/videos/pharmacity.mp4",
    time_line: "April 2nd, 2024 - April 18th, 2024 (waiting for Backend)",
    deploy_url: "https://pharmacity-clone-client.vercel.app",
    source_url: "https://github.com/duydien0902/Pharmacity_clone_client",
    thumbnail: "/images/pharmacity.png",
    isDone: false,
  },
  {
    id: idScroll.PORTFOLIO,
    title: "portfolio",
    description:
      "Explore my portfolio, crafted with NextJS, highlighting my expertise in frontend and backend development through real-world projects.",
    tech_stack: ["NextJS", "TailwindCSS", "Shadcn/ui"],
    video_url: "/videos/portfolio.mp4",
    time_line: "October 2nd - October 6th",
    deploy_url: "https://portfolio-pied-xi-58.vercel.app",
    source_url: "https://github.com/duydien0902/portfolio",
    thumbnail: "/images/portfolio.png",
    isDone: true,
  },
  {
    id: idScroll.ADMIN_ASSISTANT,
    title: "admin assistant",
    description:
      "This is an Admin Assistant. It’s role is to help adminstrator manage tasks, employees, clients, businesses. It can query data and perform action in Monday.com, search files.",
    tech_stack: [
      "NextJS",
      "TailwindCSS",
      "Shadcn/ui",
      "Api OpenAi",
      "NodeJS",
      "ExpressJS",
    ],
    video_url: "/videos/admin-assistant.mp4",
    time_line: "april 15th, 2024 - present",
    deploy_url: "",
    source_url: "",
    thumbnail: "/images/admin_assistant.png",
    isDone: true,
  },
];
